# Utilisation de l'image officielle PostgreSQL
FROM postgres:15

# Définition des variables d'environnement pour créer la base de données
# ENV POSTGRES_DB=monapi
# ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=postgres

# Exposer le port 5432 (PostgreSQL)
EXPOSE 5432

# Commande par défaut pour démarrer PostgreSQL
CMD ["postgres"]
